# Generated by Django 3.2 on 2022-01-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20220118_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Added_by',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number1',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number2',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number3',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
