# Generated by Django 3.2 on 2022-01-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20220118_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number1',
            new_name='another_number',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number2',
            new_name='office_number',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number3',
            new_name='work_number',
        ),
    ]
