# Generated by Django 3.2 on 2022-01-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20220118_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='another_number',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
