# Generated by Django 3.2 on 2022-02-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_contact_another_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
